"""Initial Postgres Schema

Revision ID: 8aa9a8a12c0c
Revises: 
Create Date: 2026-08-25 09:20:29.085503+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aa9a8a12c0c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('employee_id', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('face_encoding', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_employee_id'), ['employee_id'], unique=True)

    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'suspended', name='tenant_status', create_constraint=True), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('vehicle_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('number_plate', sa.String(length=50), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('camera_name', sa.String(length=100), nullable=False),
    sa.Column('location_spot', sa.String(length=100), nullable=False),
    sa.Column('evidence_reference', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_uuid', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('first_seen', sa.Time(), nullable=False),
    sa.Column('last_seen', sa.Time(), nullable=False),
    sa.Column('camera_name', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['employee_uuid'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memberships',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.Enum('operator', 'supervisor', 'installer', 'oem_admin', 'platform_admin', name='role_enum', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('recognition_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_uuid', sa.Uuid(), nullable=True),
    sa.Column('employee_id', sa.String(length=100), nullable=True),
    sa.Column('employee_name', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('camera_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_uuid'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recognition_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recognition_history_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recognition_history_timestamp'), ['timestamp'], unique=False)

    op.create_table('sites',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('address_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sites_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_sites_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('cameras',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('protocol', sa.String(length=50), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('stream_path', sa.String(length=255), nullable=False),
    sa.Column('credential_reference', sa.String(length=255), nullable=True),
    sa.Column('stream_profile', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('pending_test', 'active', 'offline', 'error', name='camera_status_enum', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cameras_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cameras_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('detection_class', sa.String(), nullable=False),
    sa.Column('confidence_threshold', sa.Float(), nullable=False),
    sa.Column('zone_configuration', sa.JSON(), nullable=True),
    sa.Column('schedule_configuration', sa.JSON(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.create_index('ix_rules_site_id', ['site_id'], unique=False)
        batch_op.create_index('ix_rules_tenant_id', ['tenant_id'], unique=False)

    op.create_table('detection_zones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('camera_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('zone_type', sa.String(length=50), nullable=False),
    sa.Column('polygon_points', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('alert_on_entry', sa.Boolean(), nullable=False),
    sa.Column('alert_on_loiter', sa.Boolean(), nullable=False),
    sa.Column('loiter_seconds', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detection_zones', schema=None) as batch_op:
        batch_op.create_index('ix_detection_zones_camera_id', ['camera_id'], unique=False)
        batch_op.create_index('ix_detection_zones_tenant_id', ['tenant_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('camera_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('is_llm_verified', sa.Boolean(), nullable=False),
    sa.Column('corrected_label', sa.String(), nullable=True),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('evidence_reference', sa.String(), nullable=True),
    sa.Column('dedupe_key', sa.String(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'dedupe_key', name='uq_event_tenant_dedupe')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_camera_id', ['camera_id'], unique=False)
        batch_op.create_index('ix_events_event_type', ['event_type'], unique=False)
        batch_op.create_index('ix_events_observed_at', ['observed_at'], unique=False)
        batch_op.create_index('ix_events_site_id', ['site_id'], unique=False)
        batch_op.create_index('ix_events_state', ['state'], unique=False)
        batch_op.create_index('ix_events_tenant_id', ['tenant_id'], unique=False)
        batch_op.create_index('ix_events_track_id', ['track_id'], unique=False)

    op.create_table('event_audits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('previous_state', sa.String(), nullable=False),
    sa.Column('new_state', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_audits', schema=None) as batch_op:
        batch_op.create_index('ix_event_audits_event_id', ['event_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_audits', schema=None) as batch_op:
        batch_op.drop_index('ix_event_audits_event_id')

    op.drop_table('event_audits')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_track_id')
        batch_op.drop_index('ix_events_tenant_id')
        batch_op.drop_index('ix_events_state')
        batch_op.drop_index('ix_events_site_id')
        batch_op.drop_index('ix_events_observed_at')
        batch_op.drop_index('ix_events_event_type')
        batch_op.drop_index('ix_events_camera_id')

    op.drop_table('events')
    with op.batch_alter_table('detection_zones', schema=None) as batch_op:
        batch_op.drop_index('ix_detection_zones_tenant_id')
        batch_op.drop_index('ix_detection_zones_camera_id')

    op.drop_table('detection_zones')
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.drop_index('ix_rules_tenant_id')
        batch_op.drop_index('ix_rules_site_id')

    op.drop_table('rules')
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cameras_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_cameras_site_id'))

    op.drop_table('cameras')
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sites_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_sites_name'))

    op.drop_table('sites')
    with op.batch_alter_table('recognition_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recognition_history_timestamp'))
        batch_op.drop_index(batch_op.f('ix_recognition_history_employee_id'))

    op.drop_table('recognition_history')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_tenant_id'))

    op.drop_table('memberships')
    op.drop_table('attendance_records')
    op.drop_table('vehicle_records')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_name'))

    op.drop_table('tenants')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_employee_id'))

    op.drop_table('employees')
    # ### end Alembic commands ###
